version: '3.3'

services:

  web:
    image: blackonwhite-1
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/blackonwhite
#    volumes:
#      - ./webapp:/opt/webapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=black_white_game
      - SERVER_URL=${HEROKU_SERVER_URL}
      - DB_PLATFORM=postgresql

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=black_white_game
    ports:
      - '5432:5432'
    expose:
      - '5432'

#      MYSQL_DATABASE: 'db'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'



